version: '3.8'
services:
  frontend:
    build: .
    container_name: danny-blog-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  artalk_data: 